<!-- Helper functions -->
<%
  function perso(strPerso) {
   var strStart = '<' + '%';
   var strEnd = '%' + '>';
   return strStart + strPerso + strEnd;
  }
  var begin = '&lt;' + '%';
  var end = '%' + '&gt;';
  
  function bloc(strPerso)
  {
    var strStart = '<' + '%' + '@ include view="';
    var strEnd = '" %' + '>';
    return strStart + strPerso + strEnd;
  }
%>

<!-- Main Body -->
<h3 style="margin: 24px 32px 16px;"><%= ctx.@HEADER %></h3>
<p style="margin: 24px 32px 16px;">
  <%= perso('for each (item in rtEvent.ctx.sale.items.item) {') %>
  <strong><%= ctx.@ITEM %></strong>: <%=perso('=item.name') %>, <strong><%= ctx.@PRICE %></strong>: <%= perso('=item.displayPrice') %> <br>
  <%= perso('}') %>
</p>
<h4 style="margin: 24px 32px 16px;"><%= ctx.@TOTAL_PRICE %>: <%=perso('=rtEvent.ctx.sale.totalPrice') %></h4>