<%

function perso(strPerso) {
 var strStart = '<' + '%';
 var strEnd = '%' + '>';
 return strStart + strPerso + strEnd;
}
var begin = '&lt;' + '%';
var end = '%' + '&gt;';

  function bloc(strPerso)
{
  var strStart = '<' + '%' + '@include view="';
  var strEnd = '" %' + '>';
  return strStart + strPerso + strEnd;
}

%>
<%=bloc('ssgMessageCenterCommonFunctions')%>
<%=perso('=formatDateMC(rtEvent.ctx.order.createdAt,"test-gb")')%>
<table>
	<tr>
		<th>Col1</th>
		<th>Col2</th>
	</tr>
	<tr>
		<td>Hello</td>
		<td>Goodbye</td>
	</tr>
</table>