<%

function perso(strPerso) {
 var strStart = '<' + '%';
 var strEnd = '%' + '>';
 return strStart + strPerso + strEnd;
}
var begin = '&lt;' + '%';
var end = '%' + '&gt;';

  function bloc(strPerso)
{
  var strStart = '<' + '%' + '@include view="';
  var strEnd = '" %' + '>';
  return strStart + strPerso + strEnd;
}

%>
<%=bloc('TestFunctions')%>

<table>
	<tr>
		<th>Col1</th>
		<th>Col2</th>
	</tr>
	<tr>
		<td>Hello</td>
		<td><%=perso('=test()')%>
</td>
	</tr>
</table>